command:
  - du

rules:
  - pattern: ^du.*
    name: Cannot read STDERR, not working
    colors: [red]

  - pattern: \s+[\.\/]+([\w\s\-\_\.]+)(\/.*)?$
    name: Path
    colors: [default, bold blue, blue]

  - pattern: ^\d{1,3}\s
    name: Size 'K'
    colors: [green]

  - pattern: ^ ?\d*[.,]?\dKi?\s
    colors: [green]

  - pattern: ^\d{4,6}\s
    name: Size 'M'
    colors: [yellow]

  - pattern: ^ ?\d*[.,]?\dMi?\s
    colors: [yellow]

  - pattern: ^\d{7,9}\s
    name: Size 'G'
    colors: [red]

  - pattern: ^ ?\d*[.,]?\dGi?\s
    colors: [red]

  - pattern: ^\d{10,12}\s
    name: Size 'T'
    colors: [bold red]

  - pattern: ^ ?\d*[.,]?\dTi?\s
    colors: [bold red]

  - pattern: (.*)\s+(total)$
    name: Total
    colors: [bold yellow on_blue]
