command:
  - iptables
  - ip6tables

rules:
  - pattern: ^Chain\s(\S+)\s\(.*$
    name: Chains Custom name
    colors: [white, bold bright_blue]

  - pattern: ^Chain\s(INPUT|OUTPUT|FORWARD)\s
    name: Chains FILTER table
    colors: [unchanged, bold yellow]

  - pattern: ^Chain\s(PREROUTING|POSTROUTING|INPUT|OUTPUT)\s
    name: Chains NAT|MANGLE table
    colors: [unchanged, bold yellow]

  - pattern: (pkts|target|num).*
    name: 2row Title
    colors: [bold black]

  - pattern: ACCEPT
    name: JUMP Destiny ----------------------------------------------------------------
    colors: [bright_green]

  - pattern: DROP
    colors: [bright_red]

  - pattern: REJECT
    colors: [red]

  - pattern: QUEUE
    colors: [on_red white]

  - pattern: RETURN
    colors: [on_green white]

  - pattern: MASQUERADE
    colors: [bright_magenta]

  - pattern: (LOG|ULOG)
    colors: [bright_cyan]

  - pattern: DNAT
    colors: [magenta]

  - pattern: SNAT
    name: '------------------------------------------------------------------------------'
    colors: [dark magenta]

  - pattern: \stcp\s
    name: tcp
    colors: [bold cyan]

  - pattern: \sudp\s
    name: udp
    colors: [bold magenta]

  - pattern: \sicmp\s
    name: icmp
    colors: [cyan]

  - pattern: \sall\s
    name: all
    colors: [red]

  - pattern: \sdpts?:([^\s]*)(\s|$)
    name: dpt
    colors: [default, bold yellow]

  - pattern: \s(\[goto\])
    name: Goto
    colors: [default, on_blue bold white]

  - pattern: \smasq ports:\s(\d+)-?(\d+)?
    name: masq ports
    colors: [default, bold yellow, bold yellow]

  - pattern: ctstate\s(\S+)
    name: ctstate
    colors: [default, blue]

  - pattern: (!)?((?:\d{1,3}\.){3}(?:\d{1,3}))(?:\/|:)?(\d+)?
    name: IP
    colors: [default, red, bright_white, magenta]

  - pattern: \s(anywhere|0.0.0.0/0)\s
    name: anywhere
    colors: [bright_black]

  - pattern: \((\d+) references\)
    name: (Num references)
    colors: [default, bright_green]
